unzip 6.0d05s Beta
Origin: http://antinode.info/ftp/info-zip//unz60d05s

diff --git a/unix/configure b/unix/configure
--- a/unix/configure
+++ b/unix/configure
@@ -4,7 +4,7 @@
 
 # configure: Guess values for system-dependent variables
 # Output the flag definitions to the file "flags".
-# Parameters: $1 = $CC, $2 = $CFLAGS
+# Parameters: $1 = $(CC), $2 = $(CFLAGS), $3 = $(DIR_BZ2LIB)
 # To construct unzip automatically using this file, type
 # "make -f unix/Makefile generic".
 # If this fails, then type "make list" to get a list of special targets.
@@ -12,18 +12,16 @@
 trap "rm -f conftest* core a.out; exit 1" 1 2 3 15
 
 CC=${1-cc}
-CFLAGS=${2-"-I. -DUNIX"}
+CFLAGS=${2}
+CFLAGSR=${CFLAGS}
+DIR_BZ2LIB=${3-"bzip2"}
+CFLAGS="${CFLAGS} -I. -DUNIX"
 LFLAGS1=""
-LFLAGS2=""
 LN="ln -s"
 
 CFLAGS_OPT=''
 
-# bzip2
-IZ_BZIP2=${3-}
-CFLAGS_BZ=''
-
-echo "Check C compiler type (optimization option)"
+echo 'Check C compiler type (optimization options)'
 cat > conftest.c << _EOF_
 int main()
 {
@@ -52,108 +50,47 @@ _EOF_
     echo '  DEC C (-O3)'
     CFLAGS_OPT='-O3'
   else
-    echo '  Other (gcc?) (-O2)'
-    CFLAGS_OPT='-O2'
+    cat > conftest.c << _EOF_
+int main()
+{
+#ifdef __GNUC__
+   bad code
+#endif
+#ifndef __hpux
+   bad code
+#endif
+   return 0;
+}
+_EOF_
+    $CC $CFLAGS -c conftest.c > /dev/null 2>/dev/null
+    if test $? -eq 0; then
+      # HP-UX, not GCC.  Lame bundled or real ANSI compiler?
+      cat > conftest.c << _EOF_
+int main()
+{
+#ifndef __HP_cc
+   bad code
+#endif
+   return 0;
+}
+_EOF_
+      $CC $CFLAGS -c conftest.c > /dev/null 2>/dev/null
+      if test $? -eq 0; then
+        echo '  HP-UX ANSI C (+O3 +Onolimit)'
+        CFLAGS_OPT='+O3 +Onolimit'
+      else        
+        echo '  HP-UX Bundled C (no opt)'
+      fi
+    else
+      echo '  Other (gcc?) (-O2)'
+      CFLAGS_OPT='-O2'
+    fi
   fi
 fi
 
 # optimization flags
 if test -n "${CFLAGS_OPT}"; then
-  CFLAGS="${CFLAGS} ${CFLAGS_OPT}"
-  CFLAGS_BZ="${CFLAGS_BZ} ${CFLAGS_OPT}"
-fi
-
-# bzip2
-
-CC_BZ="${CC}"
-LIB_BZ=''
-LD_BZIP2=''
-echo "Check bzip2 support"
-if test -n "${IZ_BZIP2}"; then
-  echo "  Check for bzip2 compiled library in IZ_BZIP2 (${IZ_BZIP2})"
-  if test -f "${IZ_BZIP2}/libbz2.a"; then
-#
-#   A bzip2 library built with BZ_NO_STDIO should have an
-#   unresolved external, "bz_internal_error".  The default,
-#   full-function library will not mention it.
-#
-    nm ${IZ_BZIP2}/libbz2.a | grep bz_internal_error > /dev/null
-    if test $? -eq 0; then
-      echo "    Found bzip2 BZ_NO_STDIO library, ${IZ_BZIP2}/libbz2.a"
-    else
-      echo "    Found bzip2 library, ${IZ_BZIP2}/libbz2.a,"
-      echo "      but library not compiled with BZ_NO_STDIO"
-      echo "    WARNING:  We recommend using a bzip2 library compiled"
-      echo "      with BZ_NO_STDIO defined for proper error handling"
-      echo "    Please see the Zip installation instructions in bzip2/install.txt"
-      echo "    Continuing anyway with standard bzip2 library..."
-    fi
-    if test -f "${IZ_BZIP2}/bzlib.h"; then
-      CFLAGS="${CFLAGS} -I${IZ_BZIP2} -DBZIP2_SUPPORT"
-      LD_BZIP2="-L${IZ_BZIP2} -lbz2"
-      echo "-- Found bzip2 library - linking in bzip2"
-    else
-      echo "    ${IZ_BZIP2}/bzlib.h not found"
-      echo "-- Since IZ_BZIP2 defined, skipping OS and bzip2 dir checks - no bzip2"
-    fi
-  else
-    echo "    ${IZ_BZIP2}/libbz2.a not found"
-    echo "-- Since IZ_BZIP2 defined, skipping OS and bzip2 checks - no bzip2"
-  fi
-else
-  echo "  Check for bzip2 in bzip2 directory"
-  IZ_BZIP2=bzip2
-  if test -f "${IZ_BZIP2}/libbz2.a"; then
-    nm ${IZ_BZIP2}/libbz2.a | grep bz_internal_error > /dev/null
-    if test $? -eq 0; then
-      echo "    Found bzip2 BZ_NO_STDIO library in bzip2 directory"
-    else
-      echo "    Found bzip2 library in bzip2 directory,"
-      echo "      but not built with the BZ_NO_STDIO option"
-      echo "    WARNING:  We recommend using a bzip2 library compiled"
-      echo "      with BZ_NO_STDIO defined for proper error handling"
-      echo "    Please see the Zip installation instructions"
-      echo "    Continuing anyway with standard bzip2 library..."
-    fi
-  fi
-  if test -f "bzip2/bzlib.h" -a -f "bzip2/libbz2.a"; then
-    CFLAGS="${CFLAGS} -I${IZ_BZIP2} -DBZIP2_SUPPORT"
-    LD_BZIP2="-L${IZ_BZIP2} -lbz2"
-    echo "-- Found bzip2 library - linking in bzip2"
-  else
-    if test -f "bzip2/bzlib.c" -a -f "bzip2/bzlib.h"; then
-      echo "-- No library, but found bzip2 source in bzip2 directory"
-      echo "-- Will try to build bzip2 library from source and link in"
-#
-# Arrange to build a BZ_NO_STDIO bzip2 object library using the
-# same compiler and optimization options as used for Zip, and
-# to compile and link Zip with bzip2.
-#
-      CFLAGS_BZ="${CFLAGS_BZ} -DBZ_NO_STDIO"
-      LIB_BZ="bzip2/libbz2.a"
-      CFLAGS="${CFLAGS} -I${IZ_BZIP2} -DBZIP2_SUPPORT"
-      LD_BZIP2="-L${IZ_BZIP2} -lbz2"
-    else
-      echo "  Check if OS already has bzip2 library installed"
-      cat > conftest.c << _EOF_
-#include "bzlib.h"
-int main()
-{
-  bz_stream strm;
-  BZ2_bzCompressEnd(&strm);
-  return 0;
-}
-_EOF_
-      $CC $CFLAGS -o conftest conftest.c -lbz2 > /dev/null 2>/dev/null
-      if test $? -eq 0; then
-        echo "-- OS supports bzip2 - linking in bzip2"
-        CFLAGS="${CFLAGS} -DBZIP2_SUPPORT"
-        LD_BZIP2="-lbz2"
-      else
-        echo "-- Either bzlib.h or libbz2.a not found - no bzip2"
-      fi
-    fi
-  fi
+  CFLAGSR="${CFLAGSR} ${CFLAGS_OPT}"
 fi
 
 echo Check for the C preprocessor
@@ -176,7 +113,7 @@ if eval "$CPP crc_i386.S > _crc_i386.s 2>/dev/null"; then
   if test ! -s _crc_i386.s || grep error < _crc_i386.s > /dev/null; then
     :
   elif eval "$CC -c _crc_i386.s >/dev/null 2>/dev/null" && [ -f _crc_i386.o ]; then
-    CFLAGS="${CFLAGS} -DASM_CRC"
+    CFLAGSR="${CFLAGSR} -DASM_CRC"
     CRC32OA="crc_gcc.o"
     echo "int foo() { return 0;}" > conftest.c
     $CC -c conftest.c >/dev/null 2>/dev/null
@@ -205,14 +142,14 @@ if [ $? -ne 0 ]; then
   for OPT in "-Aa -D_HPUX_SOURCE" -Xa -qlanglvl=ansi -std1 -std
   do
     $CC $CFLAGS $OPT -c conftest.c > /dev/null 2>/dev/null
-    [ $? -eq 0 ] && CFLAGS="${CFLAGS} ${OPT}" && break
+    [ $? -eq 0 ] && CFLAGSR="${CFLAGSR} ${OPT}" && break
   done
 fi
 
 echo Check for prototypes
 echo "int main(int argc, char *argv[]) { return 0; }" > conftest.c
 $CC $CFLAGS -c conftest.c > /dev/null 2>/dev/null
-[ $? -ne 0 ] && CFLAGS="${CFLAGS} -DNO_PROTO"
+[ $? -ne 0 ] && CFLAGSR="${CFLAGSR} -DNO_PROTO"
 
 # const check currently handles mips cc and non ANSI compilers.
 # does it need more ?
@@ -227,7 +164,7 @@ int main()
 }
 _EOF_
 $CC $CFLAGS -c conftest.c >/dev/null 2>/dev/null
-[ $? -ne 0 ] && CFLAGS="${CFLAGS} -DNO_CONST"
+[ $? -ne 0 ] && CFLAGSR="${CFLAGSR} -DNO_CONST"
 
 echo Check for time_t
 cat > conftest.c << _EOF_
@@ -240,7 +177,7 @@ int main()
 }
 _EOF_
 $CC $CFLAGS -c conftest.c >/dev/null 2>/dev/null
-[ $? -ne 0 ] && CFLAGS="${CFLAGS} -DNO_TIME_T"
+[ $? -ne 0 ] && CFLAGSR="${CFLAGSR} -DNO_TIME_T"
 
 echo Check for size_t
 cat > conftest.c << _EOF_
@@ -252,7 +189,7 @@ int main()
 }
 _EOF_
 $CC $CFLAGS -c conftest.c >/dev/null 2>/dev/null
-[ $? -ne 0 ] && CFLAGS="${CFLAGS} -DNO_SIZE_T"
+[ $? -ne 0 ] && CFLAGSR="${CFLAGSR} -DNO_SIZE_T"
 
 echo Check for off_t
 cat > conftest.c << _EOF_
@@ -264,7 +201,7 @@ int main()
 }
 _EOF_
 $CC $CFLAGS -c conftest.c >/dev/null 2>/dev/null
-[ $? -ne 0 ] && CFLAGS="${CFLAGS} -DNO_OFF_T"
+[ $? -ne 0 ] && CFLAGSR="${CFLAGSR} -DNO_OFF_T"
 
 # Added 11/4/2003 EG
 # Revised 8/12/04 EG
@@ -309,10 +246,40 @@ else
     echo -- no Large File Support - no 64-bit stat
   elif [ $r -eq 3 ]; then
     echo -- yes we have Large File Support!
-    CFLAGS="${CFLAGS} -DLARGE_FILE_SUPPORT"
+    CFLAGSR="${CFLAGSR} -DLARGE_FILE_SUPPORT"
   else
     echo -- no Large File Support - conftest returned $r
   fi
+fi
+
+# Added 9/5/2007 EG
+# Check for wide char for Unicode support
+echo Check for wide char support
+cat > conftest.c << _EOF_
+#include <stdlib.h>
+#include <stdio.h>
+int main()
+{
+  int wsize;
+  wchar_t *wide_string;
+
+  if ((wide_string = (wchar_t *)malloc(4 * sizeof(wchar_t))) == NULL) {
+    return 0;
+  }
+  /* get wide string */
+  wsize = mbstowcs(wide_string, "foo", 3);
+  wide_string[wsize] = (wchar_t) NULL;
+  return 1;
+}
+_EOF_
+# compile it
+$CC -o conftest conftest.c >/dev/null 2>/dev/null
+if [ $? -ne 0 ]; then
+  echo -- no Unicode support
+else
+# have wide char support
+  echo -- have wchar_t - enabling Unicode support
+  CFLAGSR="${CFLAGSR} -DUNICODE_SUPPORT"
 fi
 
 # from configure 2.4i (Onno) 12/5/04
@@ -338,13 +305,13 @@ do
   echo Check for $func
   echo "int main(){ $func(); return 0; }" > conftest.c
   $CC $BFLAG -o conftest conftest.c >/dev/null 2>/dev/null
-  [ $? -ne 0 ] && CFLAGS="${CFLAGS} -DNO_`echo $func | tr '[a-z]' '[A-Z]'`"
+  [ $? -ne 0 ] && CFLAGSR="${CFLAGSR} -DNO_`echo $func | tr '[a-z]' '[A-Z]'`"
 done
 
 echo Check for memset
 echo "int main(){ char k; memset(&k,0,0); return 0; }" > conftest.c
 $CC -o conftest conftest.c >/dev/null 2>/dev/null
-[ $? -ne 0 ] && CFLAGS="${CFLAGS} -DZMEM"
+[ $? -ne 0 ] && CFLAGSR="${CFLAGSR} -DZMEM"
 
 echo Check for errno declaration
 cat > conftest.c << _EOF_
@@ -356,7 +323,7 @@ main()
 }
 _EOF_
 $CC $CFLAGS -c conftest.c >/dev/null 2>/dev/null
-[ $? -ne 0 ] && CFLAGS="${CFLAGS} -DNO_ERRNO"
+[ $? -ne 0 ] && CFLAGSR="${CFLAGSR} -DNO_ERRNO"
 
 echo Check for directory libraries
 cat > conftest.c << _EOF_
@@ -374,7 +341,7 @@ if [ $? -ne 0 ]; then
   if [ ${OPT} ]; then
     LFLAGS2="${LFLAGS2} ${OPT}"
   else
-    CFLAGS="${CFLAGS} -DNO_DIR"
+    CFLAGSR="${CFLAGSR} -DNO_DIR"
   fi
 fi
 
@@ -395,14 +362,14 @@ do
    $CPP conftest.c > /dev/null 2>/dev/null
    [ $? -eq 0 ] && OPT="-DHAVE_`echo $inc | tr '[a-z]./' '[A-Z]__'`" && break
 done
-CFLAGS="${CFLAGS} ${OPT}"
+CFLAGSR="${CFLAGSR} ${OPT}"
 
 echo Check for non existent include files
 for inc in stdlib.h stddef.h unistd.h fcntl.h string.h
 do
    echo "#include <$inc>" > conftest.c
    $CPP conftest.c >/dev/null 2>/dev/null
-   [ $? -ne 0 ] && CFLAGS="${CFLAGS} -DNO_`echo $inc | tr '[a-z]./' '[A-Z]__'`"
+   [ $? -ne 0 ] && CFLAGSR="${CFLAGSR} -DNO_`echo $inc | tr '[a-z]./' '[A-Z]__'`"
 done
 
 echo Check for term I/O include file
@@ -413,7 +380,7 @@ do
    $CPP conftest.c > /dev/null 2>/dev/null
    [ $? -eq 0 ] && OPT="-DHAVE_`echo $inc | tr '[a-z]./' '[A-Z]__'`" && break
 done
-CFLAGS="${CFLAGS} ${OPT}"
+CFLAGSR="${CFLAGSR} ${OPT}"
 
 # needed for AIX (and others ?) when mmap is used
 echo Check for valloc
@@ -426,7 +393,7 @@ main()
 }
 _EOF_
 $CC ${CFLAGS} -c conftest.c > /dev/null 2>/dev/null
-[ $? -ne 0 ] && CFLAGS="${CFLAGS} -DNO_VALLOC"
+[ $? -ne 0 ] && CFLAGSR="${CFLAGSR} -DNO_VALLOC"
 
 echo Check for /usr/local/bin and /usr/local/man
 BINDIR=$HOME/bin
@@ -440,13 +407,13 @@ MANDIR=manl
 echo Checking for OS specialties
 if [ -f /usr/bin/hostinfo ]; then
   if /usr/bin/hostinfo | grep NeXT > /dev/null; then
-    CFLAGS="${CFLAGS} -posix"
+    CFLAGSR="${CFLAGSR} -posix"
     LFLAGS1="${LFLAGS1} -posix -object"
   fi
 # XXX ATT6300, Cray
 elif [ -f /xenix ]; then
   if uname -p | grep 286 > /dev/null; then
-    CFLAGS="${CFLAGS} -LARGE -Mel2 -DMEDIUM_MEM -DWSIZE=16384 -DNO_VOID"
+    CFLAGSR="${CFLAGSR} -LARGE -Mel2 -DMEDIUM_MEM -DWSIZE=16384 -DNO_VOID"
     LFLAGS1="${LFLAGS1} -LARGE -Mel2"
   fi
 elif uname -X >/dev/null 2>/dev/null; then
@@ -461,16 +428,16 @@ else
      OSF1|ULTRIX)
         echo Check for -Olimit option
         $CC ${CFLAGS} -Olimit 1000 -o conftest conftest.c >/dev/null 2>/dev/null
-        [ $? -eq 0 ] && CFLAGS="${CFLAGS} -Olimit 1000"
+        [ $? -eq 0 ] && CFLAGSR="${CFLAGSR} -Olimit 1000"
         ;;
-     HP-UX)
-        echo Check for +Onolimit option
-        $CC ${CFLAGS} +Onolimit -o conftest conftest.c >/dev/null 2>/dev/null
-        [ $? -eq 0 ] && CFLAGS="${CFLAGS} +Onolimit"
-        ;;
-     SunOS)
-        CFLAGS="${CFLAGS} -D_FILE_OFFSET_BITS=64"
-        ;;
+###     HP-UX)
+###        echo Check for +Onolimit option
+###        $CC ${CFLAGS} +Onolimit -o conftest conftest.c >/dev/null 2>/dev/null
+###        [ $? -eq 0 ] && CFLAGSR="${CFLAGSR} +Onolimit"
+###        ;;
+###     SunOS)
+###        CFLAGSR="${CFLAGSR} -D_FILE_OFFSET_BITS=64"
+###        ;;
   esac
 fi
 
@@ -479,8 +446,26 @@ ln -s /dev/null null > /dev/null 2>/dev/null || LN=ln
 
 rm -f a.out conftest.c conftest.o conftest null
 
-echo CF=\"${CFLAGS}\" CRCA_O=\"${CRC32OA}\" AS=\"${CC} -c\" \
-      CC_BZ=\"${CC_BZ}\" CFLAGS_BZ=\"${CFLAGS_BZ}\" \
-      IZ_BZIP2=\"${IZ_BZIP2}\" LD_BZIP2=\"${LD_BZIP2}\" \
-      LIB_BZ=\"${LIB_BZ}\" > flags
-#
+
+# bzip2
+
+echo "Check bzip2 support"
+D_USE_BZ2=""
+LIBBZ2=""
+L_BZ2=""
+DIR_BZ2LIB=${3-"bzip2"}
+echo "  Check for bzip2 in bzip2 directory"
+if test -f "${DIR_BZ2LIB}/bzlib.c" -a -f "${DIR_BZ2LIB}/bzlib.h"; then
+   echo "-- Found bzip2 source in ${DIR_BZ2LIB}/ directory"
+   echo "-- Will try to build bzip2 library from source and link in"
+   LIBBZ2="${DIR_BZ2LIB}/libbz2.a"
+   D_USE_BZ2="-DUSE_BZIP2"
+   L_BZ2="-lbz2"
+else
+   echo "-- bzip2 sources not found - no bzip2 support"
+fi
+
+
+echo CF=\"${CFLAGSR}\" CRCA_O=\"${CRC32OA}\" AS=\"${CC} -c\" \
+       D_USE_BZ2=\"${D_USE_BZ2}\" L_BZ2=\"${L_BZ2}\" \
+       LIBBZ2=\"${LIBBZ2}\"  > flags
