unzip 6.10c08a_l_sY Beta
Origin: http://antinode.info/ftp/info-zip//unzip610c08a_l_sY.zip

diff --git a/unix/Makefile._bad b/unix/Makefile._bad
--- a/unix/Makefile._bad
+++ b/unix/Makefile._bad
@@ -1,8 +1,8 @@
 #==============================================================================
 # unix/Makefile
-# - For UnZip, fUnZip, UnZipSFX, and ZipInfo            Revised: 2014-01-21
+# - For UnZip, fUnZip, UnZipSFX, and ZipInfo            Revised: 2013-11-29
 #
-# Copyright (c) 2004-2014 Info-ZIP.  All rights reserved.
+# Copyright (c) 2004-2013 Info-ZIP.  All rights reserved.
 #
 # See the accompanying file LICENSE, version 2009-Jan-2 or later (the
 # contents of which are also included in zip.h) for terms of use.  If,
@@ -1204,18 +1204,28 @@ $(PROD)/flags_bz: $(PROD)/flags
 #----------------------------------------------------------------------------
 
 clean:
-	@if unix/unsafe_prod.sh "$(PROD)"; then \
-          echo "Won't clean absolute (/x) or rising (../) PROD: $(PROD)"; \
+	if [ "$(PROD)" = '.' ]; then \
+          clean_prod=1; \
         else \
-          echo "rm -f \"$(PROD)\"/*.o \"$(PROD)\"/*.a $(UNZIP_PPGMS)"; \
-          rm -f "$(PROD)"/*.o "$(PROD)"/*.a $(UNZIP_PPGMS); \
-          echo "rm -f \"$(PROD)\"/flags \"$(PROD)\"/flags_bz"; \
-          rm -f "$(PROD)"/flags "$(PROD)"/flags_bz; \
-          echo "rm -f $(PROD)/manout"; \
-          rm -rf "$(PROD)"/manout; \
+          clean_prod=0; \
+        fi; \
+        export clean_prod
+	echo $${clean_prod}
+	if [ $${clean_prod} -eq 0 ]; then \
+          echo "$(PROD)" | grep -e '^/' -e '../' > /dev/null 2>&1; \
+          if [ $$? -eq 0 ]; then clean_prod=0; fi \
         fi
-#       # Remove empty $(PROD) directory.
-	if [ -d "$(PROD)" ]; then \
+	echo $${clean_prod}
+	@if [ $${clean_prod} -eq 0 ]; then \
+          echo "Can't clean: absolute (/) or rising (../) PROD: $(PROD)"; \
+        fi
+	if [ $${clean_prod} -ne 0 ]; then \
+          rm -f $(PROD)/*.o $(PROD)/*.a $(UNZIP_PPGMS); \
+          rm -f $(PROD)/flags $(PROD)/flags_bz; \
+          rm -rf $(PROD)/manout; \
+        fi
+	@# Remove empty $(PROD) directory.
+	if [ $${clean_prod} -ne 0 -a -d "$(PROD)" ]; then \
           ls -1 "${PROD}"/* > /dev/null 2>&1 || \
           rm -r "$(PROD)" ; \
         fi
diff --git a/unix/configure b/unix/configure
--- a/unix/configure
+++ b/unix/configure
@@ -4,9 +4,9 @@
 
 #==============================================================================
 # unix/configure: Detect feature support and pass that information to Makefile.
-# - For UnZip, UnZipSFX, fUnZip and ZipInfo             Revised: 2013-11-29
+# - For UnZip, UnZipSFX, fUnZip and ZipInfo             Revised: 2014-01-28
 #
-# Copyright (c) 2004-2013 Info-ZIP.  All rights reserved.
+# Copyright (c) 2004-2014 Info-ZIP.  All rights reserved.
 #
 # See the accompanying file LICENSE, version 2009-Jan-2 or later (the
 # contents of which are also included in zip.h) for terms of use.  If,
@@ -321,13 +321,18 @@ elif [ -f "${PROD}" ]; then
   echo "^^ Directory name exists as an ordinary file.  Unable to build."
   exit 1
 else
-  echo "-- Creating build root directory."
-  ${MKDIR} ${PROD}
-  status=$?
-  if [ $status -ne 0 ]; then
-    echo ''
-    echo "^^ Directory creation failed (${status})."
-    exit $status
+  if unix/unsafe_prod.sh "${PROD}"; then
+    echo "^^ Unsafe absolute (/x) or rising (../) PROD: ${PROD}"
+    exit 13
+  else
+    echo "-- Creating build root directory."
+    ${MKDIR} ${PROD}
+    status=$?
+    if [ $status -ne 0 ]; then
+      echo ''
+      echo "^^ Directory creation failed (${status})."
+      exit $status
+    fi
   fi
 fi
 
@@ -2768,8 +2773,18 @@ echon "Check ${CF_TEST}..."
 cat > conftest.c << _EOF_
 int main() { return 0; }
 _EOF_
-${CC_TST} ${CFLAGS} ${CF_TEST} -o conftest conftest.c >/dev/null 2>/dev/null
+${CC_TST} ${CFLAGS} ${CF_TEST} -o conftest conftest.c > /dev/null \
+ 2> conftest.err
 status=$?
+if [ $status -eq 0 ]; then
+  grep -i unknown < conftest.err > /dev/null 2> /dev/null
+  status=$?
+  if [ $status -eq 0 ]; then
+    status=666;
+  else
+    status=0
+  fi
+fi
 if [ $status -eq 0 ]; then
   echo '  Yes.'
   CFLAGS_TST="${CFLAGS_TST} ${CF_TEST}"
@@ -2783,8 +2798,18 @@ echon "Check ${CF_TEST}..."
 cat > conftest.c << _EOF_
 int main() { return 0; }
 _EOF_
-${CC_TST} ${CFLAGS} ${CF_TEST} -o conftest conftest.c >/dev/null 2>/dev/null
+${CC_TST} ${CFLAGS} ${CF_TEST} -o conftest conftest.c > /dev/null \
+ 2> conftest.err
 status=$?
+if [ $status -eq 0 ]; then
+  grep -i unknown < conftest.err > /dev/null 2> /dev/null
+  status=$?
+  if [ $status -eq 0 ]; then
+    status=666;
+  else
+    status=0
+  fi
+fi
 if [ $status -eq 0 ]; then
   echo '  Yes.'
   CFLAGS_TST="${CFLAGS_TST} ${CF_TEST}"
