unzip 6.10c08a_l_s3x Beta
Origin: http://antinode.info/ftp/info-zip//unzip610c08a_l_s3x.zip

diff --git a/unix/zipgrep b/unix/zipgrep
--- a/unix/zipgrep
+++ b/unix/zipgrep
@@ -27,18 +27,48 @@ if test $? -eq 0; then
   unzopts3='-aa'
 fi
 
+optl0=''
+optl1=''
+optl2=''
+optl3=''
+optlc=0
+optok=1
+opts=""
 pat=""
-opt=""
+list=0
+silent=0
 while test $# -ne 0; do
-  case "$1" in
-  -e | -f) opt="$opt $1"; shift; pat="$1";;
-  -*)      opt="$opt $1";;
-   *)      if test -z "$pat"; then
-             pat="$1"
-           else
-             break;
-           fi;;
-  esac
+  if test $optok -ne 0; then
+    case "$1" in
+    -e | -f) opts="$opts $1"; shift; pat="$1";;
+    --)      optok=0;;
+    --*)     if test "$1" = '--files-with-matches'; then
+               list=1
+             else
+               if test "$1" = '--no-filename'; then
+                 silent=1
+                 opts="$opts h"
+               else
+                 if test $optlc -lt 4; then
+                   eval optl${optlc}="$1"
+                   optlc=` expr $optlc + 1 `
+                 fi
+               fi
+             fi;;
+    -*)      opts="$opts $1";;
+     *)      if test -z "$pat"; then
+               pat="$1"
+             else
+               break;
+             fi;;
+    esac
+  else
+    if test -z "$pat"; then
+      pat="$1"
+    else
+      break;
+    fi
+  fi
   shift
 done
 
@@ -49,17 +79,15 @@ if test $# = 0; then
 fi
 zipfile="$1"; shift
 
-list=0
-silent=0
-opt=`echo "$opt" | sed -e 's/ //g' -e 's/-//g'`
-case "$opt" in
-  *l*) list=1; opt=`echo $opt | sed s/l//`
+opts=`echo "$opts" | sed -e 's/ //g' -e 's/-//g'`
+case "$opst" in
+  *l*) list=1; opts=`echo $opts | sed s/l//`
 esac
-case "$opt" in
+case "$opts" in
   *h*) silent=1
 esac
-if test -n "$opt"; then
-  opt="-$opt"
+if test -n "$opts"; then
+  opts="-$opts"
 fi
 
 status_grep_global=1
@@ -76,13 +104,13 @@ for i in `$unzip -Z1 "$zipfile" ${1+"$@"} | sed -e 's/\\\\/\\\\\\\\/g' `; do
   if test $list -eq 1; then
     # "-l": Show only the archive member name, not the matching line(s).
     $unzip $unzopts1 $unzopts2 $unzopts3 "$zipfile" "$i" | \
-     egrep $opt "$pat" > /dev/null && echo "$i"
+     egrep $opts $optl0 $optl1 $optl2 $optl3 "$pat" > /dev/null && echo "$i"
     status_grep=$?
   elif test $silent -eq 1; then
     # "-h": Show only the matching line(s), not the archive member name.
-    # ("-s" in "opt" will silence "egrep", stopping all output.)
+    # ("-s" in "opts" will silence "egrep", stopping all output.)
     $unzip $unzopts1 $unzopts2 $unzopts3 "$zipfile" "$i" | \
-     egrep $opt "$pat"
+     egrep $opts $optl0 $optl1 $optl2 $optl3 "$pat"
     status_grep=$?
   else
     # Escape (or re-escape) shell-special characters in the archive
@@ -96,19 +124,28 @@ for i in `$unzip -Z1 "$zipfile" ${1+"$@"} | sed -e 's/\\\\/\\\\\\\\/g' `; do
     exec 4>&1
     status_grep=` ( \
      ( $unzip $unzopts1 $unzopts2 $unzopts3 "$zipfile" "$i" | \
-     egrep $opt "$pat" 1>&4 ; echo $? >&3 ) 4>&1 | \
+     egrep $opts $optl0 $optl1 $optl2 $optl3 "$pat" 1>&4 ; \
+     echo $? >&3 ) 4>&1 | \
      sed "s|^|${i}:|" 1>&4 \
      ) 3>&1 `
   fi
 
   # Save the primary command status.  (May be the grep status.)
   sts=$?
+  if test -z "$status_grep"; then
+    status_grep=${sts}
+  fi
   # If this grep status was zero, set the global grep status to zero.
   test "$status_grep" -eq 0 && status_grep_global=0
   # If this grep status was not zero or one, exit now.
   test "$status_grep" -gt 1 && exit "$status_grep"
 
 done
+
+# If "sts" was not set, then assume disaster.  (UnZip failed?)
+if test -z "$sts"; then
+  exit 2
+fi
 
 # If "sts" is good (0), then exit with the global grep status.
 # Else, when "sts" is bad, exit with the worst status we can find.
